name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install
        run: npm install
      - name: Starting app
        run: npm start &
      - name: Percy Test
        run: "npm run test:ci"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}